### ISSUE TITLE
Dump config file from current connections

### ISSUE THREAD

**Issue by markk** [eras/pw-connections#3]
I just came across this project when considering writing my own replacement for aj-snapshot. It looks great, thanks! 

A really useful feature would be the ability to write a config file from the current state of the graph - this would save a lot of time for complex situations with lots of connections.

**Comment by eras** [comment]
So I added this function to the master branch. You activate this with the switch `--dump`.

Can you give it a shot?

**Comment by markk** [comment]
Looks great, thanks! Although it probably shouldn't require a --config argument, is that possible?

**Comment by eras** [comment]
Good point. I'll fix that.

**Comment by markk** [comment]
And one more request - would it be possible to sort the links by src string? I had a go at this but my rust is very ... rusty...

**Comment by eras** [comment]
I believe that also this is now in the master :).

**Comment by markk** [comment]
Perfect, thanks.
