### ISSUE TITLE
Multichannel links

### ISSUE THREAD

**Issue by markk** [eras/pw-connections#4]
Another useful feature would be expansion of multichannel connections. e.g.:

```
- src: "Source:capture_0"
  dst: "Sink:playback_0"
- src: "Source:capture_1"
  dst: "Sink:playback_1"
```

might be written using a regex pattern:

```
- src: "Source:capture_[0,1]"
  dst: "Sink:playback_[0,1]"
```

**Comment by eras** [comment]
It seems the idea would be to have the capture groups to be equal, so this would then work:

```
- src: "Source:capture_([01])"
  dst: "Sink:playback_(.)"
```

(could also be `(0|1)`)

and I guess this would be useful, then?

I actually don't recall having used this tool outside midi connections so I don't have experience on or need for routing audio channels :).

**Comment by markk** [comment]
Usually, but not always. Some clients number ports differently, so you might have:

- 1, 2, 3, ...
- 0, 1, 2, ...
- FL, FR, ...

**Comment by markk** [comment]
On reflection, "regex" is probably the wrong concept - it's more like parallel shell expansion. Something like this:

```
- src: "Source:capture_{0..3}"
  dst: "Sink:playback_{FL,FR,RL,RR}"
```

would link:

- Source:capture_0 -> Sink:playback_FL
- Source:capture_1 -> Sink:playback_FR
- Source:capture_2 -> Sink:playback_RL
- Source:capture_3 -> Sink:playback_RR

**Comment by eras** [comment]
Looks reasonable and useful. It would probably be expanded (and checked for validity, e.g. the number of expansions match) when loading configuration to limit the scope of changes. There would probably be a hard limit of one `{}` per entry.

**Comment by markk** [comment]
Yes, exactly.

**Comment by eras** [comment]
I added support for simple ranges like {1..4} and {a,b,c,d} (not for any kind of combinations of them, however) to master.

Does this work for you?

**Comment by markk** [comment]
Thank  you - this is working great!

**Comment by eras** [comment]
I just realized my very example output in the README would benefit from supporting multiple (but still parallel) expansions in the config file:

```
"Novation SL MkIII 1:(capture_0) Novation SL MkIII MIDI 1"
"Novation SL MkIII 1:(capture_1) Novation SL MkIII MIDI 2"
"Novation SL MkIII 1:(capture_2) Novation SL MkIII MIDI 3"
```

So I guess I'll do that as well at some point :).
